1. Одномерные массивы

создайте и выведите последовательность чисел от 10 до 20 с постоянным
шагом, длина последовательности - 21.

In [1]:
import numpy as np

In [2]:
array1 = np.linspace(10, 20, 21) #21 число  от 10 до 20
array1

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

2. Операции над одномерными массивами

1). Создайте массив чисел от −2π−2π до 2π2π. (????)

In [3]:
import math

In [4]:
arr2 = np.arange(-2*(math.pi)-2*(math.pi), 2*(math.pi)*2*(math.pi))
arr2

array([-12.56637061, -11.56637061, -10.56637061,  -9.56637061,
        -8.56637061,  -7.56637061,  -6.56637061,  -5.56637061,
        -4.56637061,  -3.56637061,  -2.56637061,  -1.56637061,
        -0.56637061,   0.43362939,   1.43362939,   2.43362939,
         3.43362939,   4.43362939,   5.43362939,   6.43362939,
         7.43362939,   8.43362939,   9.43362939,  10.43362939,
        11.43362939,  12.43362939,  13.43362939,  14.43362939,
        15.43362939,  16.43362939,  17.43362939,  18.43362939,
        19.43362939,  20.43362939,  21.43362939,  22.43362939,
        23.43362939,  24.43362939,  25.43362939,  26.43362939,
        27.43362939,  28.43362939,  29.43362939,  30.43362939,
        31.43362939,  32.43362939,  33.43362939,  34.43362939,
        35.43362939,  36.43362939,  37.43362939,  38.43362939,
        39.43362939])

2). Посчитайте сумму поэлементных квадратов синуса и косинуса для данного массива.

In [5]:
sum = (np.sin(arr2)**2 + np.cos(arr2)**2)
sum

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

3). С помощью np.all проверьте, что в ответе только единицы.

In [6]:
np.all(sum.round() == 1)

np.True_

3. Двумерные массивы

создайте матрицы
Посчитайте их поэлементное и матричное произведения.

In [7]:
matrix1 = np.array([(-3, 4), (4, 3)])
matrix1

array([[-3,  4],
       [ 4,  3]])

In [8]:
matrix2 = np.array([(2, 1), (1, 2)])
matrix2

array([[2, 1],
       [1, 2]])

Посчитайте их поэлементное и матричное произведения.

In [9]:
# поэлементное произведение

print(matrix1 * matrix2)

[[-6  4]
 [ 4  6]]


In [10]:
# матричное произведение

print(matrix1 @ matrix2)
print(matrix2 @ matrix1)

[[-2  5]
 [11 10]]
[[-2 11]
 [ 5 10]]


In [11]:
np.matrix(matrix1) * np.matrix(matrix2) # другим способом матричное произведение

matrix([[-2,  5],
        [11, 10]])

В статистике и машинном обучении часто приходится иметь с функцией RSS, которая
вычисляется по формуле где — координаты одномерного вектора
— координаты одномерного вектора a. Посчитайте RSS для y = (1,2,3,4,5), a = (3,2,1,0,−1)

In [12]:
y = np.array([1, 2, 3, 4, 5])
a = np.array([3, 2, 1, 0, -1])

In [13]:

rss = np.sum((y - a)**2)
rss


np.int64(60)

4. Тензоры (многомерные массивы)

Подумайте, массив какого размера получится, если перемножить массив 4×1×3 и
массив 12×1. Убедитесь на практике в правильности вашего ответа.

In [14]:
r1 = 4, 1, 3 # размерность матрицы
a = np.ones(r1) # матрица из единиц
r2 = 12, 1
b = np.ones(r2)

array4 = a * b
print((array4))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
array4.shape

(4, 12, 3)

В машинном обучении есть модель линейной регрессии, для которой "хорошее" решение
считается по следующей формуле:
Вычислите th для матриц X и y. I — единичная матрица размерности 3, λ=0.1

In [16]:
x = np.array([(-3, 4, 1), (4, 3, 1)])
x

array([[-3,  4,  1],
       [ 4,  3,  1]])

In [17]:
y = np.array([(10), (12)])
y

array([10, 12])

In [18]:
I = np.eye(3) # типа единичная матрица
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:


L = 0.1
inv = np.linalg.inv(x.T @ x + L * I) # типа обратная матрица
th = inv @ x.T @ y
th


array([0.68478852, 2.80148778, 0.81180812])

9. Суммы Эйнштейна

Создайте матрицы . Посчитайте tr


In [20]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
b = np.array([[7, 8], [9, 10]])
b

array([[ 7,  8],
       [ 9, 10]])

In [22]:
np.sum(np.diag(a @ b @ b @ a.T))

np.int64(26583)